[project]
name = "line-discrimination-vigilance-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "klibs",
]

[tool.uv.sources]
klibs = { git = "https://github.com/a-hurst/klibs" }
